[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "16"
  VITE_API_URL = "https://fzone-api.onrender.com/api"
  ROLLUP_NATIVE = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200